### ISSUE TITLE
Installation of Q# dependants in linux mint

### ISSUE THREAD

**Issue by sushantp** [microsoft/iqsharp#107]
I am trying to install Q# python in linux mint 19. 
While passing command: "dotnet iqsharp install", I am getting the following error: The required library libhostfxr.so could not be found. Do I need windows operating system only. I am using Linux Mint 19.3.

**Comment by cgranade** [comment]
(Note: Since the IQ# repo is where Python interoperability is implemented, I've moved this issue from the samples repo to help make it easier to find. Thanks!)

**Comment by harshitgarg22** [comment]
Hello
I'm getting a similar error.

> A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/home/$USERNAME/.dotnet/tools/.store/microsoft.quantum.iqsharp/0.11.2004.2825/microsoft.quantum.iqsharp/0.11.2004.2825/tools/netcoreapp3.1/any/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].
The .NET Core runtime can be found at:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=solus.4.1-x64

I've install dotnet using snap on Solus 4.1 if that makes a difference.

**Comment by rmshaffer** [comment]
Thank you for reporting! This appears to be a .NET Core installation problem, and there is a solution to this issue here: https://github.com/microsoft/iqsharp/issues/147. If that doesn't work, or if you have additional issues with IQ# beyond that, please follow up and/or file a new issue.

Closing this one.
