### ISSUE TITLE
Exception : "`jupyter-kernelspec` not found" while installing iqsharp however it exists on PATH

### ISSUE THREAD

**Issue by thisisraghavkumar** [microsoft/iqsharp#112]
While installing QDK for use with python as described at https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall, on executing `dotnet iqsharp install` I get the following exception

```cmd
Exception: Jupyter command `jupyter-kernelspec` not found.
```

However, when I ran `jupyter-kernelspec` command on cmd it did work indicating that it exists along the PATH.

**Comment by rmshaffer** [comment]
As discussed in [this StackOverflow post](https://stackoverflow.com/questions/61097406/jupyter-kernelspec-not-found-while-installing-iqsharp-however-it-exists-on-pat/61129593), it sounds like this is a side effect of your `PATHEXT` environment variable containing a trailing semicolon. This causes Jupyter to interpret 'empty string' as a valid executable file extension, and therefore it fails to automatically append `.exe` when searching for `jupyter-kernelspec`.

I get the same behavior when appending a trailing semicolon to `PATHEXT` on my device.

Removing the trailing semicolon from your `PATHEXT` environment variable should work around the Jupyter issue.

Please reopen this issue if you are still having the problem!
