### ISSUE TITLE
DumpMachine() Meas. Pr. bars do not rendered correctly

### ISSUE THREAD

**Issue by vivanwin** [microsoft/iqsharp#123]
When using Dumpmachine() the Meas. Pr. bars are not rendered correctly. When running the [Qubit](https://github.com/microsoft/QuantumKatas/tree/master/tutorials/Qubit) tutorial kata, only the first two bars are rendered correctly and the look is inconsistent over different browsers. I have attached screenshots for different browsers.
On Binder the bars are rendered correctly. 

System specs:
Notebook server: 6.0.2
Python: 3.7.3
iqsharp: 0.11.2003.3107
Jupyter Core: 1.2.36563.0
.NET Runtime: .NETCoreApp,Version=v3.1

Chrome:
![image](https://user-images.githubusercontent.com/25651976/79771006-7a313180-832e-11ea-9fa1-157ab9d3eb51.png)

Old edge:
![image](https://user-images.githubusercontent.com/25651976/79771138-aba9fd00-832e-11ea-9c1e-2dfef5b58dbd.png)

Chromium edge:
![image](https://user-images.githubusercontent.com/25651976/79771227-c7ad9e80-832e-11ea-9ef0-4d778f0e25c2.png)

**Comment by rmshaffer** [comment]
Thanks for reporting, @vivanwin. Unfortunately I'm not able to reproduce this in any of the browsers you mentioned, using the same installed package versions as you. Is there any more information you can provide? For example, could you provide the HTML your browser sees for the areas that are behaving incorrectly? (right-click -> Inspect in Chrome/Chromium)

**Comment by vivanwin** [comment]
Hi @rmshaffer 
The HTML looks good 
`<progress max="100" value="50,000000000000014" style="width: 100%;">
                                </progress>`

If you need more info let me know.

**Comment by rmshaffer** [comment]
Thanks, this is indeed the problem. The `value` attribute should use a period as the decimal symbol, per [HTML5 floating-point number spec](https://www.w3.org/TR/2011/WD-html5-20110525/common-microsyntaxes.html#valid-floating-point-number).  As we just discussed, it looks like your regional settings are set to display a comma as the decimal symbol, and the iqsharp visualization code is incorrectly using this format setting when emitting the `<progress>` element.
