### ISSUE TITLE
Pylint errors when using qsharp package

### ISSUE THREAD

**Issue by hros** [microsoft/iqsharp#125]
q# sdk examples raise import errors in vscode linter

for example copying the examples from the installation guide
[hello_world](https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall)
[host.py](https://docs.microsoft.com/en-us/quantum/quickstart?tabs=tabid-python)

into a vscode q# project gives the following errors
![image](https://user-images.githubusercontent.com/2613469/80301059-56e10900-87aa-11ea-9c68-003ade951190.png)

running the code works as expected

everything (vscode, q# extension, python, q# package) has been updated to the latest version

**Comment by cgranade** [comment]
After investigating, we've decided to close this for now, as this seems to be a limitation in how pylint handles `sys.meta_path`, such that we cannot likely resolve the problem on our end. We would suggest using pylint comments to disable the `import-error` check on these lines in particular. Please feel free to reopen this issue if there's additional information or context, of if you feel that we've missed something. Thank you!
