### ISSUE TITLE
Unable to import operations from Q# namespace in python host file

### ISSUE THREAD

**Issue by gianelgado12** [microsoft/iqsharp#135]
I am using a python host file from which I call Q# operation from a Q# file in the same folder. A week ago it was working fine but today whenever I run the the host file I get the following error:

<img width="339" alt="Error" src="https://user-images.githubusercontent.com/41168973/80835531-f8a89180-8bc0-11ea-900d-428d784ae5c0.PNG">

I am using Visual Studio Code

 - OS: Windows 10 

Below is a screenshot giving the relevant version information:
<img width="577" alt="VersionInfo" src="https://user-images.githubusercontent.com/41168973/80835943-c3507380-8bc1-11ea-900a-2f0cd9d6a604.PNG">

**Comment by rmshaffer** [comment]
@gianelgado12, thank you for reporting this! Would you mind sharing your Q# source code to help diagnose the issue?

**Comment by gianelgado12** [comment]
Sure @rmshaffer here is a zip file with the Q# file and its corresponding python host
[HW2.zip](https://github.com/microsoft/iqsharp/files/4566161/HW2.zip)

**Comment by rmshaffer** [comment]
Thanks @gianelgado12! It looks like you may have a syntax error in your Q# code. Specifically, your `createBellPair` method expects one argument of type `Qubit[]`, but in line 84 of your .qs file, you are passing two arguments of type `Qubit`. If you make the following change to pass an argument of type `Qubit[]` instead, does this work for you?

```
            for(i in 0..n-1){
                createBellPair([qs[i], qs[i+n]]);
            }
```

Notice the additional square brackets around `[qs[i], qs[i+n]]`.

**Comment by gianelgado12** [comment]
Yes that was it thank you for your help!
