### ISSUE TITLE
Query Regarding Installation of iqsharp on windows 10.

### ISSUE THREAD

**Issue by Samar-080301** [microsoft/iqsharp#153]
**Describe the bug**
How can I install the iqsharp kernel for using qsharp module in python?

**System information**
 - OS: Windows 10 Home

**Additional context**
When I'm running 'import qsharp' in python, it's showing an error as 'iqsharp kernel not found'.

**Comment by tcNickolas** [comment]
[Q# installation docs](https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall) has the instructions - please let us know if they don't work for you.

**Comment by rmshaffer** [comment]
Thanks for the feedback and thanks for trying IQ#! Closing this issue, as I believe the question is answered by the documentation @tcNickolas provided.

**Comment by Samar-080301** [comment]
> [Q# installation docs](https://docs.microsoft.com/en-us/quantum/install-guide/pyinstall) has the instructions - please let us know if they don't work for you.

It is not showing the method of creating the iqsharp kernel in windows, only the bash method is provided over there!

**Comment by rmshaffer** [comment]
@Samar-080301, those instructions should also work from a Windows command prompt or from PowerShell. Sorry that the commands say 'Bash' above them, please disregard that.
