### ISSUE TITLE
Unable to uninstall or update Microsoft.Quantum.IQsharp

### ISSUE THREAD

**Issue by n33r4j** [microsoft/iqsharp#169]
I was working on the Quantam Katas Tutorial - [Single-qubit](https://github.com/microsoft/QuantumKatas/blob/master/tutorials/SingleQubitGates) gates via Jupyter Notebooks on my local directory where it was required to run a cell containing,
`%package Microsoft.Quantum.Katas::0.11.2006.403` before starting. 

However, since my package versions, ` Microsoft.Quantum.Standard::0.11.2004.2825 ` and ` Microsoft.Quantum.Katas::0.11.2006.403 ` did not match, I proceeded with the instructions and ran `dotnet tool uninstall microsoft.quantum.iqsharp -g` . 

This failed and shows 
`Failed to uninstall tool package 'microsoft.quantum.iqsharp': Access to the path 'C:\Users\neera\.dotnet\tools\.store\microsoft.quantum.iqsharp\0.11.2004.2825' is denied.`

The update command `dotnet tool update -g Microsoft.Quantum.IQSharp` also fails showing the same error.

I had a somewhat similiar issue earlier #149 where my Qsharp kernel failed to start due to a permission error.

Any help would be great.

**Jupyter**
```jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.3
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3 
```
**IQsharp**
```
iqsharp: 0.11.2004.2825
Jupyter Core: 1.3.52077.0
.NET Runtime: .NETCoreApp,Version=v3.1
```

**System information**
 - OS: Windows 10
 - Browser: Firefox

**Comment by cgranade** [comment]
On Windows, the IQ# kernel can be locked if you have a notebook still open, preventing you from uninstalling or updating it. Does this persist after you close all running Q# notebooks and Python programs interoperating with Q#?

**Comment by n33r4j** [comment]
Yes, sorry. I did not have this problem the last time I performed updates or uninstalls of IQsharp which is why I thought it was odd.

**Comment by rmshaffer** [comment]
Closing this. Thanks for reporting!
