### ISSUE TITLE
Errors emitted during Python initialization when Q# code depends on additional packages

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/iqsharp#171]
**Describe the bug**
The first run of Python programs that import and use Q# packages via `qsharp.packages.add()` will emit a bunch of compilation errors during the `import qsharp` step, even if the program is correct and it compiles and runs successfully.

**To Reproduce**
1. Download one of the `MachineLearning' samples from the [Quantum](https://github.com/microsoft/Quantum) repo, e.g., the [wine sample](https://github.com/microsoft/Quantum/tree/master/samples/machine-learning/wine).
2. With the `qsharp` Python package already installed, run `python host.py` to execute the sample.
3. Notice the many compilation errors emitted due to missing namespaces, types, and identifiers before the program actually begins to execute successfully.
```
(qsharp) PS C:\qdk\quantum\samples\machine-learning\wine> python host.py
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6104: No namespace with the name "Microsoft.Quantum.MachineLearning" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6104: No namespace with the name "Microsoft.Quantum.MachineLearning.Datasets" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6005: No type with the name "ControlledRotation" exists in any of the open namespaces.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6005: No type with the name "LabeledSample" exists in any of the open namespaces.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6005: No type with the name "SamplingSchedule" exists in any of the open namespaces.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6005: No type with the name "ControlledRotation" exists in any of the open namespaces.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS6005: No type with the name "ControlledRotation" exists in any of the open namespaces.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "WineData" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "ValidateSequentialClassifier" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "SequentialModel" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "WineData" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "TrainSequentialClassifier" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "SequentialModel" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "DefaultTrainingOptions" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "LearningRate" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "MinibatchSize" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "Tolerance" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "NMeasurements" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "MaxEpochs" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "VerboseMessage" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "CombinedStructure" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "LocalRotationsLayer" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "LocalRotationsLayer" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "CyclicEntanglingLayer" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "PartialRotationsLayer" exists.
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with the name "SamplingSchedule" exists.
Adding package Microsoft.Quantum.MachineLearning::0.11.2006.403.Ready to train.
  Beginning training at start point #0...
    Pre-encoding samples...
    Beginning epoch 1.
        Beginning minibatch 0 of 25.
      Estimating gradient at sample 0...
      Estimating gradient at sample 1...
            Observed good parameter update... estimating and possibly commiting.
        Beginning minibatch 1 of 25.
      Estimating gradient at sample 0...
      Estimating gradient at sample 1...
```

**Expected behavior**
These errors should not be emitted. The program is written correctly and runs successfully.

Note that on subsequent runs of the same program, these errors are not emitted, since the package has now been loaded into the cached workspace.

Ideally we need a way to specify required packages at initialization time, so that IQ# kernel initialization during `import qsharp` knows which packages to load. This is potentially related to #24, since we may need something like a `.csproj` file in the current folder that specifies required package references.

**Screenshots**
An example of the errors output to the console:
![image](https://user-images.githubusercontent.com/3620100/84904719-7f77d780-b064-11ea-9300-d07bbb39b73f.png)

**System information**
 - OS: Windows 10
 - Version: 
    ```
    (qsharp) C:\qdk> python -c "import qsharp; print(qsharp.component_versions())"
    {'iqsharp': LooseVersion ('0.11.2006.403'), 'Jupyter Core': LooseVersion ('1.3.60623.0'), '.NET 
    Runtime': LooseVersion ('.NETCoreApp,Version=v3.1'), 'qsharp': LooseVersion ('0.11.2006.403')}
    ```

**Additional context**
Errors like these were seen in a few StackOverflow questions recently:
- https://quantumcomputing.stackexchange.com/questions/12457/q-quantum-machinelearning-namespace-doesnt-exist-error
- https://quantumcomputing.stackexchange.com/questions/12494/attempting-to-use-the-quantummachinelearning-repositry-with-vscode-and-now-impor
- https://quantumcomputing.stackexchange.com/questions/12520/q-error-no-namespace-with-the-name-microsoft-quantum-machinelearning-exists

**Comment by anpaz-msft** [comment]
It's great to see this closed!

**Comment by rmshaffer** [comment]
This should now work when using the `<IQSharpLoadAutomatically>true</IQSharpLoadAutomatically>` property in the .csproj to load the required package(s) at initialization time. See https://docs.microsoft.com/en-us/quantum/user-guide/host-programs?tabs=tabid-python#using-q-code-from-other-projects-or-packages for more details.
