### ISSUE TITLE
Python package should not find .qs files recursively.

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/iqsharp#20]
Currently, the Python qsharp module recursively tries to find all `.qs` files in all subdirectories of the current working folder, which is causing some confusion as that's not normal Python behavior.

We should just load the .qs files under the current working folder and find some other mechanism to import/load files from other folders.

**Comment by ScottCarda-MS** [comment]
PR for this issue is #49.

**Comment by cgranade** [comment]
Closing since #49 is now in, and as the rest of the work is tracked as #24.
