### ISSUE TITLE
'None' returned when return values are more than 7 in \\

### ISSUE THREAD

**Issue by shreyankkr** [microsoft/iqsharp#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System information**

**Additional context**

**Comment by shreyankkr** [comment]
Look like created by mistake!

**Comment by shreyankkr** [comment]
Please delete this issue. Look like I do not have permissions to do.

**Comment by rmshaffer** [comment]
@shreyankkr, no worries, deleting it now!
