### ISSUE TITLE
MockAzureWorkspace tests should load provider packages using MockNugetPackages or fixed package version

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/iqsharp#223]
**Describe the bug**
Currently, MockAzureWorkspace tests load the default version of each of the provider packages. This doesn't work well for end-to-end CI builds, where `iqsharp` is built prior to the provider packages.

**Expected behavior**
When the AzureEnvironment is set to Mock, `ActiveTarget.PackageName` should specify a fixed version such that the tests can successfully load an existing version of these packages.

When fixing this, we should remove the `MockAzureWorkspace` check here:

https://github.com/microsoft/iqsharp/blob/c18ee78db8c9428d5210a4e788aed6b90fddcc08/src/AzureClient/AzureClient.cs#L292-L296

**Comment by anpaz-msft** [comment]
Notce another approach could be to setup use the MockReferences class for IReferences when running unittests. The MockReferences doesn't download the packages from nuget, though. It just keeps track of what was called.
