### ISSUE TITLE
Running dotnet test consumes too much memory

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/iqsharp#224]
**Describe the bug**
Each unit test does not de-allocate the memory that was allocated during the test. Because we have ~90 tests, running `dotnet test` eventually consumes over 6 GB of RAM, despite the fact that each test run on its own consumes no more than ~100 MB.

**Expected behavior**
Each unit test should fully de-allocate its memory when it finishes.

**Additional context**
As a temporary workaround for CI, we have implemented #222, which breaks up the test run into multiple invocations of `dotnet test`. That workaround can be removed once this underlying issue is resolved.

**Comment by cgranade** [comment]
We believe this has been fixed by recent performance improvements and by porting to .NET 6, but please feel free to re-open if there's a regression of if you have any additional information. Thank you!
