### ISSUE TITLE
iqsharp-base Docker image tag should use new SemVer-style version

### ISSUE THREAD

**Issue by vivanwin** [microsoft/iqsharp#255]
### Problem
When you run the updateQDKVersion.ps1 script, the update for the Dockerfile gives a wrong version format for the container repository. 
The new version code for the rest of the repo is in this format `mcr.microsoft.com/quantum/iqsharp-base:x.xx.xxxxxxxx` however the container register has this format `mcr.microsoft.com/quantum/iqsharp-base:x.xx.xxxx.xxxx`. 

### Solution
The update script should be updated to make sure the right format is used in the Docker file.

**Comment by tcNickolas** [comment]
(Transferring the issue to the iqsharp repo, since the fix will involve changing the version of the entry to match the versions in the rest of places rather than modifying the update script to accommodate the version difference.)

**Comment by rmshaffer** [comment]
The iqsharp-base Docker image tag is being set here:
https://github.com/microsoft/iqsharp/blob/10726ae2af98942dc7104a745fb6105046088766/build/pack.ps1#L89

**Comment by rmshaffer** [comment]
This work was completed as of the 0.12.20082513 QDK release. The Docker image is now published in the format `mcr.microsoft.com/quantum/iqsharp-base:x.xx.xxxxxxxx`.
