### ISSUE TITLE
Q# notebook syntax highlighting doesn't work after browser refresh

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/iqsharp#267]
**Describe the bug**
In a Q# notebook, after refreshing the browser (or opening the same notebook in another tab), syntax highlighting no longer works.

**To Reproduce**
1. Open a Q# notebook. See that syntax highlighting works as expected.
2. Refresh the browser.
3. Notice that syntax highlighting is gone. If you restart the kernel, then syntax highlighting works again.

**Expected behavior**
Syntax highlighting should be re-initialized each time the page loads.

**Screenshots**
Example of syntax highlighting not working:
![image](https://user-images.githubusercontent.com/3620100/90195106-8594e680-dd7d-11ea-8bd1-397ece5a0d30.png)

**System information**
 - OS: Windows
 - Browser: Edge
 - Version: 0.12.20072031

**Comment by anjbur** [comment]
This is unfortunately a limitation of Jupyter notebooks. We encourage people facing this to use the hosted Jupyter notebook interface in Azure Quantum where syntax highlighting is built in. Otherwise, closing this as it's not something we can fix on our side.
