### ISSUE TITLE
Refractoring ConfigurationSource.cs for consistency with naming convention used in the project

### ISSUE THREAD

**Issue by Manvi-Agrawal** [microsoft/iqsharp#295]
Currently the interfaces and concrete implementation for various classes are in separate files. Some examples are :
 Snippet : Isnippet.cs, Snippet.cs
 CompilerService : ICompilerService, CompilerService, etc.

However, ConfigurationSource.cs contains : 
- Implementation of interface IConfigurationSource.cs
- Concrete Implementation of interface IConfigurationSource.cs

So, it might be a good idea to separate interface and concrete implementation in different files

**Comment by rmshaffer** [comment]
Thanks @Manvi-Agrawal for filing and fixing this issue -- your contribution is appreciated!
