### ISSUE TITLE
Misc syntax highlighting errors.

### ISSUE THREAD

**Issue by cgranade** [microsoft/iqsharp#31]
**Describe the bug**
Syntax highlighting in IQ# exhibits several small issues:
- Parens before types are colored with the types.
- The `newtype` keyword is not colored.
- The `%` operator is treated as a comment.

**Screenshots**
![image](https://user-images.githubusercontent.com/31516/63063819-127b3a80-beb3-11e9-9fe1-6c57dae96ff5.png)

**System information**
 - OS: Windows 10
 - Browser: Chromium Edge

**Additional context**
![image](https://user-images.githubusercontent.com/31516/63063830-21fa8380-beb3-11e9-9a4c-dc53d6eb2abc.png)

**Comment by RutujaShirali** [comment]
Working on this now

**Comment by tcNickolas** [comment]
Resolved in #53.
