### ISSUE TITLE
iqsharp install seems to copy entire drive

### ISSUE THREAD

**Issue by adutchuser** [microsoft/iqsharp#32]
when running the command

dotnet iqsharp install

it seems to cosume all avilable diskspace
upon inspection it copies the entire  user home directory to 
C:\Users\A User\AppData\Roaming\jupyter\kernels\iqsharp

i.e. C:\Users\A User\ is copied into C:\Users\A User\AppData\Roaming\jupyter\kernels\iqsharp

**Comment by anpaz-msft** [comment]
@adutchuser, `iqsharp` is not copying the entire drive, it just tries to find all `.qs` files recursively from the local folder to include them in the current workspace.
We agreed this is not the right approach, and we have issue #20 opened to get it fixed.
Closing this particular issue as duplicated.
