### ISSUE TITLE
Error in building docker image: ADD failed: no source files were specified 

### ISSUE THREAD

**Issue by mostafatouny** [microsoft/iqsharp#329]
Hello,
First off, I would like to gratitude Microsoft on their leap supporting Linux and open-source community.

I started building q# docker image via
`sudo docker build https://raw.githubusercontent.com/microsoft/iqsharp/main/images/iqsharp-base/Dockerfile`

Unfortunately, I got the following error message
`ADD failed: no source files were specified`

It occured directly after
`Step 15/25 : ADD nugets/*.nupkg ${LOCAL_PACKAGES}/nugets/`

Here is the full log output
[log.txt](https://github.com/microsoft/iqsharp/files/5291708/log.txt)

Thank you in advance

**Comment by rmshaffer** [comment]
Hi @mostafatouny, thanks for the question! That `Dockerfile` is intended for use during the CI build in this repo, and it assumes that the build outputs are in certain paths. ([Here](https://github.com/microsoft/iqsharp/blob/249490833c5d4c0728c911eab796b7b22394ffd6/build/pack.ps1#L51-L97) is where it is used in the CI scripts.)

May I ask what you're trying to do? If you simply want to use an image, the latest IQ# Docker image is published to the Microsoft Container Registry with the tag `mcr.microsoft.com/quantum/iqsharp-base:latest`. You can download this image, use it in your own custom dockerfile, and/or use it as a devcontainer in VS Code. See here for more details: https://github.com/microsoft/iqsharp#using-iq-as-a-container

If there's something else specific you're trying to do, please let me know and I'll try to help!

**Comment by mostafatouny** [comment]
@rmshaffer,
Thank you for the quick response.

I was just trying to simply use a docker image for experimenting with quantum programming for education purposes.

I am going to pull `mcr.microsoft.com/quantum/iqsharp-base:latest` as you recommended me. I'm sure it is going to work fine as expecteded.

In addition, I suggest the tagged container registry, `mcr.microsoft.com/quantum/iqsharp-base:latest`, be more emphasized in the main page of [setting up QDK with Docker](https://docs.microsoft.com/en-us/quantum/quickstarts/) in Microsoft docs.

**Comment by mostafatouny** [comment]
Thank you for everything

**Comment by rmshaffer** [comment]
Thank you for the feedback, and thanks for trying out the QDK! Please feel free to open another issue if you run into anything else.
