### ISSUE TITLE
Access to Q# runtime diagnostics from Python

### ISSUE THREAD

**Issue by rmshaffer** [microsoft/iqsharp#332]
**Is your feature request related to a problem? Please describe.**
Q# programs can contain diagnostic callables such as `DumpMachine()`, `DumpRegister()`, and `DumpOperation()`. At runtime, these callables emit useful diagnostic information. This information is currently printed to the console and/or displayed visually in HTML-enabled clients, but cannot easily be obtained as a Python object.

**Describe the solution you'd like**
The `simulate()` API for Q# callables in Python should contain a callback function that is invoked whenever a diagnostic is emitted from the Q# runtime.

These are the `simulate()` APIs:
https://github.com/microsoft/iqsharp/blob/249490833c5d4c0728c911eab796b7b22394ffd6/src/Python/qsharp-core/qsharp/loader.py#L86-L91
https://github.com/microsoft/iqsharp/blob/249490833c5d4c0728c911eab796b7b22394ffd6/src/Python/qsharp-core/qsharp/clients/iqsharp.py#L161-L162

For example, perhaps a Python consumer could write code something like:
```python
op = qsharp.compile('...')   # compile some Q# operation containing, e.g., DumpMachine() calls

def onDiagnostic(diagnostic):
    print(diagnostic)  # "diagnostic" here contains the raw information from the emitted diagnostic

op.simulate(arg1=5, arg2=3, diagnosticCallback=onDiagnostic)  # where arg1, arg2 are the Q# arguments
```

**Additional context**
The implementation of this will likely involve plumbing into the `display_data` handler here:
https://github.com/microsoft/iqsharp/blob/249490833c5d4c0728c911eab796b7b22394ffd6/src/Python/qsharp-core/qsharp/clients/iqsharp.py#L246-L252

**Comment by anjbur** [comment]
Closed by #462
