### ISSUE TITLE
%%qsharp magic command in Python to compile Q# code

### ISSUE THREAD

**Issue by guenp** [microsoft/iqsharp#336]
**Is your feature request related to a problem? Please describe.**
Currently, to compile Q# code, there is the `qsharp.compile` function. However, this function takes a string as input. This string inherently has no code highlighting.

**Describe the solution you'd like**
It would be nice to have a `%%qsharp` magic command instead, such that we can provide syntax highlighting in the Jupyter cell.

**Describe alternatives you've considered**
Editing a .qs file in VS Code with code highlighting, and reading the file into memory could work, however, it would be nice to have the code that was run as part of the notebook.

**Additional context**
I would say this is a "nice to have"/ergonomics type of feature that would make Q# easier to use for Python developers.

**Comment by cgranade** [comment]
This has been completed as of 0.18 (June). Thank you!
