### ISSUE TITLE
Fail when import qsharp in python

### ISSUE THREAD

**Issue by dgwvfxn** [microsoft/iqsharp#355]
**Describe the bug**
After conda installation, run `% python -c "import qsharp"`,
Returns the following error message:
Preparing Q# environment...
..fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS3001: Syntax does not match any known patterns.

**To Reproduce**
In Anaconda installation, did the following things:
1.	conda create -n qsharp-env
2.	conda activate qsharp-env
3.	conda install python=3.7
4.	conda install -c quantum-engineering qsharp notebook
5.	python -c “import qsharp”

Here is the result of `conda list | grep qsharp`:
qsharp                   0.12.2010.504            py37_0    quantum-engineering
qsharp                    0.12.2010.504            py37_0    quantum-engineering
qsharp-chemistry          0.12.2010.504            pypi_0    pypi
qsharp-core               0.12.2010.504            pypi_0    pypi

**Expected behavior**
import qsharp library successfully 

**System information**
 - OS: MacOS 10.15.7
 - Conda Version: 4.9.0
 - Python Version: 3.7.9

**Comment by cgranade** [comment]
Does this work if you `import qsharp` from a new temporary directory? What `*.qs` files are in the same directory as when you get the error above?

**Comment by dgwvfxn** [comment]
Thank you! import in a clean directory without .qs files works!
