### ISSUE TITLE
Python import qsharp error

### ISSUE THREAD

**Issue by cgranade** [microsoft/iqsharp#36]
**This issue was originally filed by @patrickxli as MicrosoftDocs/quantum-docs-pr#473.**

When I import qsharp in Python, I see the following error:

```
import qsharp
Preparing Q# environment...
...................Traceback (most recent call last):

File "", line 1, in
import qsharp

File "D:\Anaconda3\lib\site-packages\qsharp_init_.py", line 119, in
client = _start_client()

File "D:\Anaconda3\lib\site-packages\qsharp\clients_init_.py", line 47, in _start_client
raise Exception("Q# environment was not available in allocated time.")

Exception: Q# environment was not available in allocated time.
```

How to fix it? Any advice?

Thanks!

**Comment by cgranade** [comment]
Thanks for filing this issue, @patrickxli! This may be an example of #20, which can cause the IQ# kernel to crash or to take a very long time to load if run directly from your home directory; which directory did you try running from?

**Comment by GitBashQuantum** [comment]
Go to the location where the site package **qsharp** is installed and go to **qsharp\clients\__init__.py** 
and change the range in the for loop from 20 to some other value greater than 20. (I chose 100).

**Comment by GitBashQuantum** [comment]
Go to the location where the site package **qsharp** is installed and go to **qsharp\clients\ __ init __.py**
and change the range in the for loop from 20 to some other value greater than 20. (I chose 100).

**Comment by emzatos** [comment]
I am also running into this issue on a docker image, I am attempting to run 'python host.py' on the chemistry samples, specifically AnalyzeHamiltonian. I'm not sure if I am able to modify the qsharp timeout value from the image, so I don't have a mitigation as of now.

**Comment by GitBashQuantum** [comment]
> I am also running into this issue on a docker image, I am attempting to run 'python host.py' on the chemistry samples, specifically AnalyzeHamiltonian. I'm not sure if I am able to modify the qsharp timeout value from the image, so I don't have a mitigation as of now.

I am not using Windows Pro or Server to support the installation of Docker. So, I am not sure of the docker image. The module in the qsharp site package has functions like FermionHamiltonian etc. but not AnalyzeHamiltonian here.

**Comment by rmshaffer** [comment]
Closing this since #49 and #154 now prevent IQ# from recursively searching all subfolders of the current folder, which should address the major issue here.

@emzatos, if you are still running into a similar error, please open a new issue with specific details on your scenario.
