### ISSUE TITLE
qsharp package for Python 3.8

### ISSUE THREAD

**Issue by sanori** [microsoft/iqsharp#366]
**Is your feature request related to a problem? Please describe.**
When I run `conda install -c quantum-engineering qsharp` on Python 3.8
the following error occurs:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - qsharp=0.13.2011.1004 -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.8
```

**Describe the solution you'd like**
Please provide iqsharp package for Python 3.8 if you do not need to stay Python 3.7.

**Describe alternatives you've considered**
I'm making iqsharp docker imager based from Python 3.7.

**Comment by rmshaffer** [comment]
Thanks for reporting! You're right the conda packages currently support only Python 3.7. There is also https://github.com/microsoft/iqsharp/issues/273 tracking this issue, so I'll close this as a duplicate.

In the meantime, if you'd like a workaround, you should be able to use the `qsharp` package on Python 3.8 if you install via `pip`. This also requires installing IQ# manually. See the instructions here:
https://docs.microsoft.com/quantum/quickstarts/install-python?tabs=tabid-dotnetcli

**Comment by sanori** [comment]
Thank you for prompt reply and workaround to use Python 3.8.
