### ISSUE TITLE
iqsharp jupyter kernel connection fails due to tornado timeout error

### ISSUE THREAD

**Issue by ms-O** [microsoft/iqsharp#387]
**Short description:**
Unable to establish connection to Q# kernel in Jupyter notebook due to tornado\websocket.py timeout

**Relevant error message:** 
    Traceback (most recent call last):
      File "C:\Users\koberm01\.conda\envs\qsharp-env\lib\site-packages\tornado\websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
    
**Steps:**
1. Follow instructions for installing the IQ# kernel using conda at https://docs.microsoft.com/en-us/quantum/quickstarts/install-jupyter?tabs=tabid-conda.  Note: launch conda prompt using Run as Admin option.
2. Launch Jupyter from conda qsharp-env
3. Create new Q# notebook with SampleQuantumRandomNumberGenerator code
4. Unable to run notebook cells due to kernel connection issue as can be seen from log below

**Expected behavior:** Being able to execute the SampleQuantumRandomNumberGenerator code in a new Q# notebook.
    
**Environment details:**
Windows 10 Enterprise Version 10.0.17763 Build 17763
conda 4.9.2 (Anaconda 64 bit installation)
python 3.7.9
tornado 6.1
iqsharp 0.14.2011.120240
jupyter-core 4.7.0
dotnet 3.1.404

**Steps taken to resolve (unsuccessful):**
a. Some research indicated that downgrading tornado to 5.1.1 may resolve the issue, but that was tried and triggered other errors so tornado was returned to 6.1.  Example: https://github.com/tornadoweb/tornado/issues/2651
b. Also tried the option to install IQ# using .NET CLI.  Installed without error but creating a new Q# Jupyter notebook produces the same error.

**Output from conda prompt (Run as Admin):**

```
(base) C:\windows\system32>conda activate qsharp-env

(qsharp-env) C:\windows\system32>python -c "import qsharp"
Preparing Q# environment...

(qsharp-env) C:\windows\system32>jupyter notebook
[I 10:00:25.072 NotebookApp] Serving notebooks from local directory: C:/ko-jupyter-notebooks
[I 10:00:25.072 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 10:00:25.073 NotebookApp] http://localhost:8888/?token=67e7d25a2acd41b9f64873b0d0ac52bb0bd9ca1584ea7434
[I 10:00:25.073 NotebookApp]  or http://127.0.0.1:8888/?token=67e7d25a2acd41b9f64873b0d0ac52bb0bd9ca1584ea7434
[I 10:00:25.074 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:00:25.240 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/koberm01/AppData/Roaming/jupyter/runtime/nbserver-12136-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=67e7d25a2acd41b9f64873b0d0ac52bb0bd9ca1584ea7434
     or http://127.0.0.1:8888/?token=67e7d25a2acd41b9f64873b0d0ac52bb0bd9ca1584ea7434
[I 10:00:39.921 NotebookApp] Kernel started: 05b90f39-524b-4b7f-a950-aec261df8be2, name: iqsharp
[I 10:00:44.680 NotebookApp] Adapting from protocol version 5.2.0 (kernel 05b90f39-524b-4b7f-a950-aec261df8be2) to 5.3 (client).
[W 10:00:49.214 NotebookApp] Nudge: attempt 10 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:00:54.214 NotebookApp] Nudge: attempt 20 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:00:59.202 NotebookApp] Nudge: attempt 30 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:04.213 NotebookApp] Nudge: attempt 40 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:09.206 NotebookApp] Nudge: attempt 50 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:14.213 NotebookApp] Nudge: attempt 60 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:19.215 NotebookApp] Nudge: attempt 70 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:24.235 NotebookApp] Nudge: attempt 80 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:29.267 NotebookApp] Nudge: attempt 90 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:34.279 NotebookApp] Nudge: attempt 100 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:39.295 NotebookApp] Nudge: attempt 110 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[W 10:01:44.282 NotebookApp] Nudge: attempt 120 on kernel 05b90f39-524b-4b7f-a950-aec261df8be2
[E 10:01:44.704 NotebookApp] Uncaught exception GET /api/kernels/05b90f39-524b-4b7f-a950-aec261df8be2/channels?session_id=e9e4538223d64b959245f8941e87102a (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/05b90f39-524b-4b7f-a950-aec261df8be2/channels?session_id=e9e4538223d64b959245f8941e87102a', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\koberm01\.conda\envs\qsharp-env\lib\site-packages\tornado\websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 10:01:45.729 NotebookApp] Replacing stale connection: 05b90f39-524b-4b7f-a950-aec261df8be2:e9e4538223d64b959245f8941e87102a
[I 10:02:39.716 NotebookApp] Saving file at /QSharpPracticeKO/TestQSharp.ipynb
```

**Screenshot of notebook:**
![image](https://user-images.githubusercontent.com/6319957/104029130-9b290380-5197-11eb-9d81-d88aeb1a84ef.png)

**Comment by mayankit** [comment]
I am also facing the same issue. Should I migrate to Qiskit. I think that has better support.

**Comment by hirokioms** [comment]
I also have the same.

(qsharp-env) PS C:\Users\hirokio> jupyter notebook
[I 22:07:34.638 NotebookApp] Serving notebooks from local directory: C:\Users\hirokio
[I 22:07:34.638 NotebookApp] Jupyter Notebook 6.1.6 is running at:
[I 22:07:34.653 NotebookApp] http://localhost:8888/?token=96d557bb173fc994ae4834561fa84f457a39fe52aa634677
[I 22:07:34.653 NotebookApp]  or http://127.0.0.1:8888/?token=96d557bb173fc994ae4834561fa84f457a39fe52aa634677
[I 22:07:34.654 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:07:34.687 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/hirokio/AppData/Roaming/jupyter/runtime/nbserver-7832-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=96d557bb173fc994ae4834561fa84f457a39fe52aa634677
     or http://127.0.0.1:8888/?token=96d557bb173fc994ae4834561fa84f457a39fe52aa634677
[I 22:07:40.680 NotebookApp] Creating new notebook in
[I 22:07:42.205 NotebookApp] Kernel started: 5f270332-cb36-4aac-98c8-6e21ec7674f8, name: iqsharp
[I 22:07:43.880 NotebookApp] Adapting from protocol version 5.2.0 (kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8) to 5.3 (client).
[W 22:07:48.492 NotebookApp] Nudge: attempt 10 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:07:53.548 NotebookApp] Nudge: attempt 20 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:07:58.568 NotebookApp] Nudge: attempt 30 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:03.670 NotebookApp] Nudge: attempt 40 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:08.723 NotebookApp] Nudge: attempt 50 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:13.806 NotebookApp] Nudge: attempt 60 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:18.860 NotebookApp] Nudge: attempt 70 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:23.883 NotebookApp] Nudge: attempt 80 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:28.950 NotebookApp] Nudge: attempt 90 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:34.019 NotebookApp] Nudge: attempt 100 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[W 22:08:39.155 NotebookApp] Nudge: attempt 110 on kernel 5f270332-cb36-4aac-98c8-6e21ec7674f8
[E 22:08:43.891 NotebookApp] Uncaught exception GET /api/kernels/5f270332-cb36-4aac-98c8-6e21ec7674f8/channels?session_id=d033e836adf64a1f8442f7a508141bd4 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/5f270332-cb36-4aac-98c8-6e21ec7674f8/channels?session_id=d033e836adf64a1f8442f7a508141bd4', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\hirokio\Anaconda3\envs\qsharp-env\lib\site-packages\tornado\websocket.py", line 956, in _accept_connection
        await open_result
    tornado.util.TimeoutError: Timeout
[W 22:08:44.921 NotebookApp] Replacing stale connection: 5f270332-cb36-4aac-98c8-6e21ec7674f8:d033e836adf64a1f8442f7a508141bd4
[I 22:09:20.300 NotebookApp] Starting buffering for 5f270332-cb36-4aac-98c8-6e21ec7674f8:d033e836adf64a1f8442f7a508141bd4

**Comment by albspe** [comment]
Same issue reported by @hirokioms. I found online the suggestion to downgrade to tornado 5.1.1. I gave that a try and now I am having the following problem:

[W 15:04:46.881 NotebookApp] Notebook SW/quantum/TestsQ#/Untitled.ipynb is not trusted
[W 15:04:46.925 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210119150429 (127.0.0.1) 17.110000ms referer=http://localhost:8888/notebooks/SW/quantum/TestsQ%23/Untitled.ipynb
[I 15:04:47.341 NotebookApp] Kernel started: 6f0921c1-70eb-4d4b-a6ec-bc28c585570a, name: iqsharp
[I 15:04:50.508 NotebookApp] Adapting from protocol version 5.2.0 (kernel 6f0921c1-70eb-4d4b-a6ec-bc28c585570a) to 5.3 (client).
[E 15:04:50.515 NotebookApp] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb8470dd560>, count=0)
    Traceback (most recent call last):
      File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/notebook/services/kernels/handlers.py", line 207, in nudge
        if self.ws_connection is None or self.ws_connection.is_closing():
    AttributeError: 'WebSocketProtocol13' object has no attribute 'is_closing'
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=TimeoutError('Timeout')>
Traceback (most recent call last):
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/websocket.py", line 757, in _accept_connection
    yield open_result
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/XXXXXX/miniconda3/envs/qsharp-env/lib/python3.7/site-packages/tornado/websocket.py", line 553, in <lambda>
    self.stream.io_loop.add_future(result, lambda f: f.result())
tornado.util.TimeoutError: Timeout

**Comment by ricardo-espinoza** [comment]
Hi all,

Thanks for reporting this issue. We're aware of this timeout error, and we're working on a fix that we expect to have available in the coming days. In the meantime, using a faster network connection can reduce the chances that you'll get affected by this bug. We'll update this issue in GitHub as soon as a fix becomes available.

- QDK Team

**Comment by ricardo-espinoza** [comment]
This issue is now resolved in QDK version 0.15.2101125897.

**Comment by lfenster** [comment]
im having this issue and am on QDK Version: 0.18.2107153439

**Comment by anjbur** [comment]
@lfenster thank you for letting us know you're seeing this problem! A new issue has been opened for it at #494. I tagged you there as well looking for debug logs of the issue, as we haven't been able to reproduce it.
