### ISSUE TITLE
Error on dotnet iqsharp install

### ISSUE THREAD

**Issue by LM726** [microsoft/iqsharp#409]
I am a newbie, so bear with me. I couldn't get Q# to work using purely VS Code, as I was told by my tutorial. So, I wanted to install the python package and run my Hello World program that way, but it just gave a ModuleNotFoundError for `from QuantumHello import SayHello`.

Then I tried this python program for debugging:
`import qsharp
qsharp.reload()
print(qsharp.get_available_operations())`
I started it using anaconda in the qsharp environment:
`(qsharp-env) C:\Users\User>python C:\Users\User\Documents\Q#\QH\start.py
{'text/plain': 'Reloading workspace.', 'application/json': '{"LastUpdated":"2021-02-12T22:49:14.0484048+01:00","IsCompleted":false,"Description":"Reloading workspace","Subtask":null}'}
[]`

Then I read somewhere I needed the dotnet iqsharp package too and this seemed reasonable enough, as python did not seem to recognize my qs-file I placed in the same folder. I then ran `dotnet tool install -g Microsoft.Quantum.IQSharp` and then wanted to proceed by running `dotnet iqsharp install`, but I got this error: 
`System.ComponentModel.Win32Exception (5): Zugriff verweigert ("Access denied" in German)
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)`

The same error occurs if trying to run `dotnet iqsharp --version` or any other `dotnet iqsharp`-command.
I even tried repairing dotnet and rerunning `dotnet tool install -g Microsoft.Quantum.IQSharp`, but that changed nothing. 

When I tried to run a command starting with `dotnet-iqsharp` it only returned `Zugriff verweigert` (Access denied).

I dont know what I've been doing wrong and if I've been soing something wrong, but I hope someone here can help me. Thank you in advance!

**Comment by guenp** [comment]
Hi @LM726, so the second issue (Access denied) is likely because you already have IQSharp installed, and because an IQ# kernel is running after you started the Python script, the file system won't let you overwrite the package. The `iqsharp` `conda` package automatically installs this so you don't have to do that manually.

As for your first issue, this could be due to a bug in the Q# code, or perhaps because the Q# operation is not actually defined anywhere. You need to add a .qs file in the same directory as your notebook file where you define the `SayHello` operation and should look something like this:

```
namespace QuantumHello
{
    operation SayHello(name: String) : Unit {
        Message($"Hello {name}!");
    }
}
```

If you do have such a file, would you mind sharing the contents? Another reason why this error shows up is if there is a bug in the Q# code.

**Comment by guenp** [comment]
@LM726 another thing we noticed is that your path contains a special character: `C:\Users\User\Documents\Q#\QH\start.py`. I was not able to reproduce this on Mac but I wonder if this is perhaps an issue on Windows; it may be worth trying out renaming your folder to `"QSharp"` instead of `"Q#"`.

**Comment by LM726** [comment]
First of all, I have changed `Q#` to `QSharp` in the path. Unfortunately, that does not appear to be the problem.

I have two files in my folder, this is what they look like at the moment:

Operation.qs:
```
namespace QuantumHello {
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    @EntryPoint
    operation SayHello() : Unit {
        Message("Hello quantum world!");
    }
}
```

start.py:
```
import qsharp
from QuantumHello import SayHello

SayHello.simulate()
#qsharp.reload()
#print(qsharp.get_available_operations())

```

When I execute the python file from the anaconda console, I get this error I mentioned previously:
```
(qsharp-env) C:\Users\Lenna>python C:\Users\Lenna\Documents\QSharp\QH\start.py
Traceback (most recent call last):
  File "C:\Users\User\Documents\QSharp\QH\start.py", line 2, in <module>
    from QuantumHello import SayHello
ModuleNotFoundError: No module named 'QuantumHello'
```

I tried removing `@EntryPoint`, but the result was the same.

**Comment by cgranade** [comment]
> First of all, I have changed `Q#` to `QSharp` in the path. Unfortunately, that does not appear to be the problem.
> 
> I have two files in my folder, this is what they look like at the moment:
> 
> Operation.qs:
> 
> ```
> namespace QuantumHello {
>     open Microsoft.Quantum.Canon;
>     open Microsoft.Quantum.Intrinsic;
> 
>     @EntryPoint
>     operation SayHello() : Unit {
>         Message("Hello quantum world!");
>     }
> }
> ```

One thing to note is that `EntryPoint` needs to have `()` following it:

```
namespace QuantumHello {
    open Microsoft.Quantum.Canon;
    open Microsoft.Quantum.Intrinsic;

    @EntryPoint()
    operation SayHello() : Unit {
        Message("Hello quantum world!");
    }
}
```

> When I execute the python file from the anaconda console, I get this error I mentioned previously:
> 
> ```
> (qsharp-env) C:\Users\Lenna>python C:\Users\Lenna\Documents\QSharp\QH\start.py
> Traceback (most recent call last):
>   File "C:\Users\User\Documents\QSharp\QH\start.py", line 2, in <module>
>     from QuantumHello import SayHello
> ModuleNotFoundError: No module named 'QuantumHello'
> ```

That's what I would expect if there was an error compiling your Q# workspace; can you share the output from `qsharp.reload`? That should show what error is causing `QuantumHello.SayHello` to not be available.

**Comment by guenp** [comment]
@LM726 thanks for giving that a try. @cgranade  is right; `EntryPoint()` requires parentheses. However, I tried reproducing your error, and I got a different error; so it looks something might still be wrong with your environment or installation.

One thing you can run to make sure that the IQ# kernel installed correctly is to run:

```python
import qsharp
qsharp.component_versions()
```

If you have the latest version installed, this should return:
```
{'iqsharp': LooseVersion ('0.15.2101125897'),
 'Jupyter Core': LooseVersion ('1.5.0.0'),
 '.NET Runtime': LooseVersion ('.NETCoreApp,Version=v3.1'),
 'qsharp': LooseVersion ('0.15.2101.125897')}
```

If any of those look off, that might be the issue.

Another thing to be aware of is that **IQ# currently requires Python 3.7**. To check your Python version, run: `python --version` in the command line.

To get you unblocked from coding in Q#, I would recommend one of the following:

1. Uninstall and re-install Q# from scratch. The best way to go would be to use `conda`. You can do this by following these steps:
a. Uninstall any non-conda IQ# installations from your machine by closing all your Jupyter notebooks and running `dotnet tool uninstall Microsoft.Quantum.IQSharp`. If this fails, that means no other IQ# version was installed and you can simply continue.
b. Create a new virtual environment using `conda create -n qsharp python=3.7 jupyter`
c. Install `qsharp` and IQ#: `conda install -c quantum-engineering qsharp`
d. Activate the conda environment: `conda activate qsharp`
e. Browse to the folder with your code and run `jupyter notebook`.

2. Use our pre-built Binder environment. Note that you won't be able to save your notebooks or files, but you can get started running Q# code right away! The link for the Binder instance is here: [https://mybinder.org/v2/gh/Microsoft/Quantum/⭐️binder](https://mybinder.org/v2/gh/Microsoft/Quantum/%E2%AD%90binder)

I hope this helps, let us know if you were able to make it work.

**Comment by LM726** [comment]
Thanks for giving the detailed instructions @cgranade @guenp . 
I had python version 3.9, so I uninstalled that and installed Python 3.7.9. I then followed your instructions:

> To get you unblocked from coding in Q#, I would recommend one of the following:
> 
> Uninstall and re-install Q# from scratch. The best way to go would be to use conda. You can do this by following these steps:
> a. Uninstall any non-conda IQ# installations from your machine by closing all your Jupyter notebooks and running dotnet tool uninstall Microsoft.Quantum.IQSharp. If this fails, that means no other IQ# version was installed and you can simply continue.
> b. Create a new virtual environment using conda create -n qsharp python=3.7 jupyter
> c. Install qsharp and IQ#: conda install -c quantum-engineering qsharp
> d. Activate the conda environment: conda activate qsharp
> e. Browse to the folder with your code and run jupyter notebook.

Unfortunately, now I simply get this massive error message when trying to run `import qsharp` in a python script from conda:

```
(qsharp) C:\Users\User>py -3.7 -c "import qsharp"
IQ# is not installed.
Please follow the instructions at https://aka.ms/qdk-install/python.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\qsharp\clients\__init__.py", line 37, in _start_client
    client.start()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\qsharp\clients\iqsharp.py", line 83, in start
    self.kernel_manager.start_kernel(extra_arguments=["--user-agent", f"qsharp.py{user_agent_extra}"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 264, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 183, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\manager.py", line 89, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\jupyter_client\kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named iqsharp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\qsharp\__init__.py", line 123, in <module>
    client = _start_client()
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\qsharp\clients\__init__.py", line 42, in _start_client
    raise IQSharpNotInstalledError(message)
qsharp.clients.IQSharpNotInstalledError: IQ# is not installed.
Please follow the instructions at https://aka.ms/qdk-install/python.
```

I tried changing the name of the kernel to `iqsharp` instead of `qsharp`, because it said in the error message `No such kernel named iqsharp`, but that made no difference. 
Unfortunately, I tried changing my python version first, so I can't give you the output of `qsharp.reload` or `qsharp.component_versions()`, as I deleted my previous installation.

> Use our pre-built Binder environment. Note that you won't be able to save your notebooks or files, but you can get started running Q# code right away! The link for the Binder instance is here: https://mybinder.org/v2/gh/Microsoft/Quantum/⭐️binder

Thank you for the tip, I will look at that.

**Comment by guenp** [comment]
@LM726, thanks for giving this a try. From your traceback, it looks like the command `(qsharp) C:\Users\User>py -3.7 -c "import qsharp"` is not picking up the correct Python installation. The python installation you're using is here: `C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages`. The error you're getting means that it is not using the Python binary in your conda environment, so it's not picking up the IQ# kernel installation correctly.

Would you mind trying this instead: `python -c "import qsharp"`?

To make sure you're using the correct Python binary, you can run `where python`, this should return something along the lines of `C:\Users\User\Anaconda3\envs\qsharp\python.exe`. It should not use `C:\Users\User\AppData\Local\Programs\Python\Python37`.

**Comment by LM726** [comment]
@guenp Yeah, sorry, I could have seen that. I didnt realize that the Q# environment had its own python binary. I did `pip install qsharp` in the environment and then executed `python -c "import qsharp"`. However, the same error occurs, just the binaries are different:
```
(qsharp) C:\Users\User>python -c "import qsharp"
IQ# is not installed.
Please follow the instructions at https://aka.ms/qdk-install/python.
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\qsharp\clients\__init__.py", line 37, in _start_client
    client.start()
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\qsharp\clients\iqsharp.py", line 83, in start
    self.kernel_manager.start_kernel(extra_arguments=["--user-agent", f"qsharp.py{user_agent_extra}"])
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\jupyter_client\manager.py", line 262, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\jupyter_client\manager.py", line 181, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\jupyter_client\manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\jupyter_client\kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named iqsharp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\qsharp\__init__.py", line 123, in <module>
    client = _start_client()
  File "C:\Users\User\anaconda3\envs\qsharp\lib\site-packages\qsharp\clients\__init__.py", line 42, in _start_client
    raise IQSharpNotInstalledError(message)
qsharp.clients.IQSharpNotInstalledError: IQ# is not installed.
Please follow the instructions at https://aka.ms/qdk-install/python.
```

By the way, `where python` in conda returns this:
```
C:\Users\User\anaconda3\envs\qsharp\python.exe
C:\Users\User\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\User\AppData\Local\Microsoft\WindowsApps\python.exe
```


Thanks for all the help!

**Comment by guenp** [comment]
@LM726 can you try `conda install -c quantum-engineering qsharp` instead of `pip install qsharp`? The former installs the IQ# kernel while the latter does not.

**Comment by LM726** [comment]
@guenp Thanks for the tip. I did that before, but now I did it again while the environment was already active, and I it seems to have worked.
> c. Install qsharp and IQ#: conda install -c quantum-engineering qsharp
> d. Activate the conda environment: conda activate qsharp


 However, I am now facing the same problem (`ModuleNotFoundError: No module named 'QuantumHello'`) as before, so I now tried the previous suggestions:

`qsharp.reload()`:
`{'text/plain': 'Reloading workspace.', 'application/json': '{"LastUpdated":"2021-02-15T08:55:37.884469+01:00","IsCompleted":false,"Description":"Reloading workspace","Subtask":null}'}`

`qsharp.get_available_operations()`:
`[]`

`qsharp.component_versions()`:
`{'iqsharp': LooseVersion ('0.13.20111004'), 'Jupyter Core': LooseVersion ('1.4.0.0'), '.NET Runtime': LooseVersion ('.NETCoreApp,Version=v3.1'), 'qsharp': LooseVersion ('0.13.2011.1004')}`

**Comment by anjbur** [comment]
@LM726 It looks like qsharp is could be hitting a compilation error before it finds the `QuantumHello` operation. Could you run `qsharp.reload()` again and capture the full output from it? That should show any compilation issues it's hitting.

**Comment by LM726** [comment]
@anjbur If I remember correctly, I sent the full output of `qsharp.reload` in my previous message:

> `{'text/plain': 'Reloading workspace.', 'application/json': '{"LastUpdated":"2021-02-15T08:55:37.884469+01:00","IsCompleted":false,"Description":"Reloading workspace","Subtask":null}'}`

**Comment by anjbur** [comment]
You can get more information from logs by setting the environment variable IQSHARP_LOG_LEVEL to Debug (for example using conda `conda env config vars set IQSHARP_LOG_LEVEL=Debug`). Closing this for now, feel free to reach out if you have more questions

**Comment by anjbur** [comment]
@LM726 I'm very sorry for the delay in response time. Could re-run `qsharp.reload()` with the log level set to debug and share the output? That ought to show any compilation issues it might be hitting. Let me know if you have any further questions!

**Comment by LM726** [comment]
Very sorry for the even longer response time. I didnt log on github for a while. 
I have changed computers since and I dont need qsharp at the moment, so I wont try to reinstall it.

Nevertheless, thanks for all your help!
