### ISSUE TITLE
Microsoft.Quantum.IQsharp package size jump from about 19Mb to 127Mb

### ISSUE THREAD

**Issue by anpaz** [microsoft/iqsharp#426]
**Describe the bug**

The Microsoft.Quantum.IQsharp package size jump from about 19Mb to 127Mb

**To Reproduce**

* Version [0.15.2102129448](https://www.nuget.org/packages/Microsoft.Quantum.IQsharp/0.15.2102129448) is 19Mb
* Version [0.15.2103133969](https://www.nuget.org/packages/Microsoft.Quantum.IQsharp/0.15.2103133969) is 127Mb

**Comment by anjbur** [comment]
Closing as this was resolved in the April release.
