### ISSUE TITLE
Syntax highlighting not working locally for conda installation

### ISSUE THREAD

**Issue by anjbur** [microsoft/iqsharp#518]
**Describe the bug**
On local Q# notebooks, syntax highlighting doesn't work on a conda installation. Syntax highlighting still shows in Binder and in a .NET CLI installation.

**To Reproduce**
1. Create a new conda environment and then open a notebook:
```
conda create -n qsharp-18.2109 -c quantum-engineering qsharp notebook
conda activate qsharp-18.2109
jupyter notebook
```
![image](https://user-images.githubusercontent.com/12237429/133168755-7544b3a6-727d-473d-8308-25f0e722f2d5.png)

2. By contrast, these steps produced the following result:
```
dotnet tool update -g Microsoft.Quantum.IQSharp
dotnet iqsharp install
jupyter notebook
```
![image](https://user-images.githubusercontent.com/12237429/133168319-4829b2f5-df4d-4fe2-93dd-f028dc95ee40.png)

**Expected behavior**
Syntax highlighting should be present for conda IQ# installations.

**System information**
 - OS: Windows 10
 - Browser: Edge
 - Version: 0.18.2109162713
 - conda: 4.10.3

**Additional context**
I tried to find which QDK version the syntax highlighting stopped working in and found some odd behavior. I initially found that highlighting worked in 0.16.2105.140472:
![16 2105](https://user-images.githubusercontent.com/12237429/133169593-b1aada34-428e-4c06-8a4c-053a1b83ef5a.PNG)

However, when I went to open this issue, the same conda environment no longer showed highlighting:
![image](https://user-images.githubusercontent.com/12237429/133169691-5839513b-e5d7-4901-8203-c69570ef249b.png)

Creating a new conda environment with the same version initially restored highlighting. However, activating that environment in a different terminal and opening a notebook showed no highlighting. Similarly, switching to the base environment and then back to the test environment in the initial terminal resulted in no syntax highlighting.

I tested a few other earlier versions as well, but no syntax highlighting was present.

**Comment by cgranade** [comment]
Thanks for opening this issue, @anjbur! We've not been able to reproduce this issue such that I'll go on and close it for now, but please feel free to reopen if you encounter a regression. Thank you!
