### ISSUE TITLE
Q# notebook and Q# Python support for sparse simulator

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/iqsharp#566]
Details are [here](https://github.com/microsoft/qsharp-runtime/pull/853#pullrequestreview-779148921) and [here](https://github.com/microsoft/qsharp-runtime/pull/853#discussion_r728496853).

**Comment by cgranade** [comment]
If I understand right, the remaining steps are as follows:

- [ ] Update `CommonNativeSimulator` in qsharp-runtime to use `MaybeDisplayDiagnostic` and `DisplayableState` (https://github.com/microsoft/qsharp-runtime/pull/898)
- [ ] Update IQ# to utilize https://github.com/microsoft/qsharp-runtime/pull/898 (#562)
- [ ] Add `SparseSimulator` to qsharp-runtime
- [ ] Add magic command and corresponding Python method to IQ# and `qsharp` for `SparseSimulator`
- [ ] Update katas to adapt to #562

Does that sound right to you?

**Comment by cgranade** [comment]
With #562 merged in, the volume of code required in each magic command (~500 line / simulator reduction). As a result, the new command for the sparse simulator will be quite small by comparison. Similarly, the new Python method to expose that through on `QSharpCallable` is about three lines:

```python
    def simulate_sparse(self, op, **kwargs) -> Any:
        kwargs.setdefault('_timeout_', None)
        return self._execute_callable_magic('simulate-sparse', op, **kwargs)
```

**Comment by kuzminrobin** [comment]
Can be closed?

**Comment by cgranade** [comment]
I think so, as of #590. We should have an issue open, however, for the consolidation of distinct simulator commands and methods as per @bettinaheim's suggestion and our earlier offline discussion.
