### ISSUE TITLE
Add support for estimate_cost

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/iqsharp#583]
**Is your feature request related to a problem? Please describe.**
Currently, the Qiskit and Cirq implementations of azure-quantum support the estimate_cost function, which can pull back the estimated cost of a job before actually submitting it. It would be great to have this same behavior in IQ#.

**Describe the solution you'd like**
%azure.estimate_cost <Name> <Args>

It would then return the estimated cost in a similar shape to the existing Qiskit + Cirq integration, which includes:

currency_code
estimated_cost
events (detailed usage breakdown)

**Comment by cgranade** [comment]
I believe as per offline discussions that this is now being considered as a service-side rather than client-side enhancement, such that I'll go on and close this issue, but please feel free to reopen it if you disagree or have any additional context. Thank you!
