### ISSUE TITLE
IQ# language version out of date?

### ISSUE THREAD

**Issue by xinyi-joffre** [microsoft/iqsharp#617]
**Describe the bug**
It currently looks like the version of IQ# is fixed to 0.14. Did we want to have this reflect the QDK version itself?

![image](https://user-images.githubusercontent.com/20933017/158856456-e4ebbcb6-cf50-4928-9fcf-821b9d0c8f38.png)

It looks like the version number was last updated during this PR to update QDK version:
https://github.com/microsoft/iqsharp/pull/375

It shows up in the hosted notebooks experience on hover, and may be useful for helping users debug, if they can quickly get the accurate version of the IQ# kernel:

![image](https://user-images.githubusercontent.com/20933017/158856751-d21a5d00-e58b-4851-b9b3-a5719ce4b7ac.png)

**Comment by cgranade** [comment]
Thanks for filing this, @xinyi-joffre! That piece of metadata is only used in the one place you highlighted in your screenshot, so it's pretty easy to miss — I agree we should fix that, though.

**Comment by anjbur** [comment]
Closing as this was updated in #639.
