### ISSUE TITLE
Random compilation errors on DistinguishUnitaries Kata

### ISSUE THREAD

**Issue by anpaz** [microsoft/iqsharp#630]
**Describe the bug**

During our e2e and release builds, running some Katas like gives this error randomly:

`CS0136 ((null):(null)): A local or parameter named '__arg1__' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter`

**To Reproduce**

The error has been reported mainly on the notebooks in the [DistinguishUnitaries Kata]( https://github.com/microsoft/QuantumKatas/tree/main/DistinguishUnitaries)

**Comment by anpaz** [comment]
This has been narrowed down to https://github.com/microsoft/qsharp-compiler/issues/1393

**Comment by cgranade** [comment]
Thanks for narrowing this down, @anpaz! Would you recommend mitigating on the IQ# side until https://github.com/microsoft/qsharp-compiler/issues/1393 is resolved, then?

**Comment by anpaz** [comment]
Yes @cgranade. Just pushed #631 to make codegen sync.

**Comment by cgranade** [comment]
Apologies, posted right before I saw the notification for the matching PR!
