### ISSUE TITLE
nest_asyncio warning when importing qsharp module

### ISSUE THREAD

**Issue by Bradben** [microsoft/iqsharp#645]
**Describe the bug**
In a clean Anaconda environment, importing the qsharp module returns a nest_asyncio warning.

**To Reproduce**
1. Install conda
2. Activate a qsharp environment
3. 'import qsharp'
4. 
Python 3.9.11 (main, Mar 30 2022, 02:45:55) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import qsharp
Preparing Q# environment...
.C:\Users\brbenefield\Anaconda3\envs\qsharp-env\lib\site-packages\nest_asyncio.py:100: RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.
  handle._run()

**Current packages**

(qsharp-env) C:\Users\brbenefield>conda list
\# packages in environment at C:\Users\brbenefield\Anaconda3\envs\qsharp-env:
\#
\# Name                    Version                   Build  Channel
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
asttokens                 2.0.5              pyhd3eb1b0_0
attrs                     21.4.0             pyhd3eb1b0_0
azure-quantum             0.24.201332              pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
bleach                    4.1.0              pyhd3eb1b0_0
ca-certificates           2022.3.29            haa95532_0
certifi                   2021.10.8        py39haa95532_2
cffi                      1.15.0           py39h2bbff1b_1
colorama                  0.4.4              pyhd3eb1b0_0
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3              py39haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
importlib-metadata        4.11.3           py39haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
ipykernel                 6.9.1            py39haa95532_0
ipython                   8.2.0            py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
iqsharp                   0.24.201332              py39_0    microsoft
jedi                      0.18.1           py39haa95532_1
jinja2                    3.0.3              pyhd3eb1b0_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter_client            7.1.2              pyhd3eb1b0_0
jupyter_core              4.9.2            py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
markupsafe                2.0.1            py39h2bbff1b_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py39h2bbff1b_1000
nbclient                  0.5.11             pyhd3eb1b0_0
nbconvert                 6.1.0            py39haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
notebook                  6.4.8            py39haa95532_0
openssl                   1.1.1n               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.2.4           py39haa95532_0
prometheus_client         0.13.1             pyhd3eb1b0_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
pure_eval                 0.2.2              pyhd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyparsing                 3.0.4              pyhd3eb1b0_0
pyrsistent                0.18.0           py39h196d8e1_0
python                    3.9.11               h6244533_2
python-dateutil           2.8.2              pyhd3eb1b0_0
pywin32                   302              py39h827c3e9_1
pywinpty                  2.0.2            py39h5da7b33_0
pyzmq                     22.3.0           py39hd77b12b_2
qdk-sim-experimental      0.24.201332              pypi_0    pypi
qsharp                    0.24.201332              pypi_0    pypi
qsharp-chemistry          0.24.201332              pypi_0    pypi
qsharp-core               0.24.201332              pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                58.0.4           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
terminado                 0.13.1           py39haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.1.1                hd3eb1b0_0
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022a                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
winpty                    0.4.3                         4
zipp                      3.7.0              pyhd3eb1b0_0

**Comment by Bradben** [comment]
@cgranade

**Comment by Bradben** [comment]
User just reported this issue as well - https://github.com/MicrosoftDocs/quantum-docs/issues/534

**Comment by cgranade** [comment]
I believe this has now been fixed by updates to pinned package versions with #685; please feel free to reopen, however, if you observe the issue again. Thank you!
