### ISSUE TITLE
Import Q# files _not_ located in same directory

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/iqsharp#67]
**Is your feature request related to a problem? Please describe.**
It seems that when importing functions and operations from a *.qs file namespace to Python, everything must be in the same directory. There also doesn't seem to be a way to change where `qsharp` is looking for those files. 

**Describe the solution you'd like**
It would be really helpful to be able to import things from other locations, so that code need not be duplicated local to each project I am working on. I would like to have a repo with common Q# code I want to reuse, that I can then in multiple other Python projects import stuff from the common Q# repo. That requires that there be a way I can tell Q# where to look for stuff to import, other than the default local directory (which is a fine default).

**Describe alternatives you've considered**
Currently, I can duplicate the Q# code everywhere, but that is really not maintainable. 

**Additional context**
n/a

**Comment by cgranade** [comment]
If I understand correctly, this is related to #24?

**Comment by crazy4pi314** [comment]
Yeah @cgranade this is totes related to #24.

One other use case/example where this feature would be really useful that I just ran into is the following. I have a bunch of sample code arranged in separate directories (one for each chapter of a book). I want to also have a separate directory of solutions to exercises (in Jupyter notebooks) for each chapter that reference the sample code for the chapter itself. Without referencing source files outside the current directory, this is not possible afaik.

**Comment by rmshaffer** [comment]
This is now possible via the `%project` magic command. See https://docs.microsoft.com/qsharp/api/iqsharp-magic/project for details.
