### ISSUE TITLE
qsharp.packages.add("Microsoft.Quantum.Numerics")

### ISSUE THREAD

**Issue by KMcGoldrick** [microsoft/iqsharp#672]
**Describe the bug**
I see the following message at runtime.

{'text/plain': 'Adding package Microsoft.Quantum.Numerics.', 'application/x-qsharp-data': '{"LastUpdated":"2022-05-19T19:47:22.7391192-04:00","IsCompleted":false,"Description":"Adding package Microsoft.Quantum.Numerics","Subtask":null}'}

**To Reproduce**
Occurs with the following code

import asyncio
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

import qsharp
qsharp.packages.add("Microsoft.Quantum.Numerics")

**Comment by cgranade** [comment]
The snippet listed above is a normal status message that displays; we definitely take the feedback, however, that the status message could be better displayed in Python sessions. We'll open a new feature request for that, and will close this in favor of that request, but please feel free to re-open this issue if there's something else we can do here outside of the proposed enhancement. Thank you for your feedback!
