### ISSUE TITLE
iqsharp could not be installed

### ISSUE THREAD

**Issue by scalablecory** [microsoft/iqsharp#68]
_From @kaiiyer on Monday, December 2, 2019 11:05:04 AM_

# Issue Title
iqsharp could not be installed

# General
.NET Core 3.0
---------------------
SDK Version: 3.0.101
---------------------
OS (Version): Parrot GNU/LINUX Release 3.11 (64-bit)

Tool 'microsoft.quantum.iqsharp' is already installed and when i try using the command "dotnet iqsharp install", I get the following error.

Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-iqsharp does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

_Copied from original issue: dotnet/core#3942_

**Comment by cgranade** [comment]
It sounds like your global tools install directory hasn't been added to your PATH environment variable. You can check by running `which dotnet-iqsharp` (note the dash) from within Bash. This is a known issue with the .NET Core SDK tool installer on Linux ([Nate McMaster's blog post has a good mitigation/workaround](https://natemcmaster.com/blog/2018/02/02/dotnet-global-tool/#gotcha-2---path).

**Comment by cgranade** [comment]
Thanks for the report, @kaiiyer. I'm going to close the issue, but please feel free to re-open if your issue persists. Thanks!
