### ISSUE TITLE
Renaming function impossible without kernel restart

### ISSUE THREAD

**Issue by adrianleh** [microsoft/iqsharp#692]
**Describe the bug**
When trying to rename a function that is defined in a cell and used in another cell, the compiler will present errors in both cells saying that it was unable to find the function in question. For example, given 2 cells:

Cell 1:
```qsharp
operation Send(alice : Qubit, payload: Qubit) : (Result, Result) {
    CNOT(payload, alice);
    H(payload);
    return (M(alice), M(payload));
}

operation Recv(bob : Qubit, (cr_x : Result, cr_z : Result)) : Unit {
    if (cr_x == One) { X(bob); }
    if (cr_z == One) { Z(bob); }
}
```

Cell 2:
```qsharp
operation PerformTeleportationOnBellState(alice : Qubit, bob : Qubit, payload : Qubit) : Unit {
    let cr = Send(alice, payload);
    Recieve(bob, cr);
}
```

renaming `Recv` into `Recieve` in the example causes the following errors:

Cell 1:
```qsharp
Error QS5022: No identifier with the name "Recv" exists.
 2 |     let cr = Send(alice, payload);
 3 |     Recv(bob, cr);
 4 | }
```
Cell 2:
```qsharp
Error QS5022: No identifier with the name "Recieve" exists.
 2 |     let cr = Send(alice, payload);
 3 |     Recieve(bob, cr);
 4 | }
```

Currently the only resolution is to restart the kernel.

**To Reproduce**
Create a notebook with cell dependencies as in the example above, run the notebook, rename a function across the notebook, rerun cells.

**Expected behavior**
Coming from python notebooks, the expected behavior would be that it is possible to rerun the first cell with no error, after which the second cell could be rerun with no error.

However, given how IQ# works if creating this behavior is not possible, there should at least be a clearer error message guiding the user to the workaround of restarting the kernel.

**Screenshots**
![Issue_rename](https://user-images.githubusercontent.com/26521502/177833637-06a7e614-b236-49fb-a801-e94d8c574afe.PNG)

**Comment by cgranade** [comment]
Thanks for the feedback! Unfortunately, this is the behavior as designed at the moment, as it's not always perfectly clear how to map Q# concepts onto Jupyter cells. While we're definitely open to revisiting that design at some point in the future, for now this is a known limitation — we will definitely take your feedback to heart, however, and consider better ways to document and communicate this behavior. Thank you!
