### ISSUE TITLE
Occasionally simulating an operation will run indefinitely and require a kernel restart to interrupt -- In VScode

### ISSUE THREAD

**Issue by HalOwens** [microsoft/iqsharp#703]
**Describe the bug**
When simulating an operation 
**To Reproduce**
1. Write an operation in a python notebook using VS code
2. Write a for loop to simulate it a couple thousand times.
3. If it completes run it again. It will run forever after a couple tries.

**Screenshots**
This code either runs in 10 seconds or runs forever. Probably 1/4 of the time it will run indefinitely. It is not isolated to this operation or code. 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/20121080/182714541-32ca1289-5d82-43f8-b3e0-a6278b1bfcc5.png">

**System information**
 - OS: Windows

**Comment by adrianleh** [comment]
A note for reproducing:
I noticed this bug comes up more frequently, when there is a lot of background activity and CPU utilization is high

**Comment by anpaz** [comment]
This should be fixed with #708, which is now released as part of the QDK 0.25.228311+
