### ISSUE TITLE
Syntax highlighting does not work in python notebooks with qsharp cells

### ISSUE THREAD

**Issue by HalOwens** [microsoft/iqsharp#704]
**Describe the bug**

There is no syntax highliting in python notebooks when using the %%qsharp magic command

**Expected behavior**

Syntax highliting
**Screenshots**

<img width="827" alt="image" src="https://user-images.githubusercontent.com/20121080/182709747-83d9ff76-b62d-4274-90b7-a1cc30c032d7.png">

**System information**
VS code QDK plugin version 0.25.222597

**Comment by cgranade** [comment]
Much appreciated for the feedback, @HalOwens! Unfortunately, the VS Code notebook UI doesn't currently allow us to set language modes on a per-cell basis, such that we do not currently have a way to fix this. As a result, I'm going to go ahead and close this as a wontfix, but we greatly appreciate your feedback nonetheless and will keep an eye out for ways to address your request in the future. Thanks!
