### ISSUE TITLE
Trace does not visualize from within python with no documentation on how to visualize the instead returned JSON

### ISSUE THREAD

**Issue by adrianleh** [microsoft/iqsharp#706]
**Describe the bug**
When using trace from python notebooks, the command only returns JSON and does not visualize the circuit.

**To Reproduce**
Run a jupyter notebook with the following content:
```python
import qsharp
```
```qsharp
%%qsharp
operation Test() : Unit {
    use q = Qubit();
    H(q);
    Reset(q);
}
```
```python
Test.trace()
```

When running the last cell there is only JSON returned with no documentation on how to visualize it.

**Expected behavior**

The circuit is visualized correctly or there is documentation on how to visualize it. Perhaps an ASCII visualization that runs in vanilla notebooks would be an option.

**Screenshots**
![image](https://user-images.githubusercontent.com/26521502/185223877-960e41f2-5697-4737-abb6-7afc29e0f8d5.png)

**System information**
 - OS: Windows 10
 - Browser: Edge
 - Version: `0.25.222597`

**Additional information**
Related documentation:
https://docs.microsoft.com/en-us/qsharp/api/iqsharp-magic/trace
https://docs.microsoft.com/en-us/python/qsharp-core/qsharp.loader.qsharpcallable#qsharp-loader-qsharpcallable-trace

**Comment by cgranade** [comment]
Thanks for the feedback, @adrianleh! I believe this will be fixed by an upcoming change to the `qsharp` interoperability package; I'll go on and leave this open until that PR is merged in, but thanks again for your report!

**Comment by cgranade** [comment]
Closing, as this should now be fixed in the latest QDK. Please feel free to re-open if you observe a regression. Thank you!
