### ISSUE TITLE
Error trying to invoke Q# operation from Python file. 

### ISSUE THREAD

**Issue by geduardo** [microsoft/iqsharp#71]
**Describe the bug**
Calling an 'Operation.qs' from a host python program in the same folder fails with the following error:

Preparing Q# environment...
fail: Microsoft.Quantum.IQSharp.Workspace[0]
      QS5022: No identifier with that name exists.

Same files and same folder were working correctly on the same computer. Weirdly, they don't work now.

**System information**
 - OS: Windows 10
- Python 3.7.4 (64bit)
 - Version: 10.0.17763

**Comment by cgranade** [comment]
Thanks for the report, @geduardo! From that error message, it sounds like there's a problem with a specific line of the Q# sources in that folder. Would you be willing to post the Q# and Python source causing the issue? Thanks!

**Comment by geduardo** [comment]
This is weird, now it is working again (using **exactly** the same code, both in Q# and in Python). It is just the code for the QRNG. You can find the specific code for Q# and Python here: 
https://review.docs.microsoft.com/en-us/quantum/quickstarts/qrng?view=qsharp-preview&branch=pr-en-us-638&tabs=tabid-python

**Comment by cgranade** [comment]
Definitely frustrating trying to nail down intermittent bugs like that, my apologies that's happening. I'll go on and close this for now, then, but please feel free to re-open if you have a reproduction. Thanks!
