### ISSUE TITLE
Katas taking 4+ mins to execute on binder

### ISSUE THREAD

**Issue by anpaz-msft** [microsoft/iqsharp#79]
For some reason, after updating to the latest QDK and launching the Katas in Binder, trying to run a %kata cell takes 4+ minutes.

We're currently investigating this.

**Comment by cgranade** [comment]
As per @anpaz-msft's report, it appears as though the affected image is `mcr.microsoft.com/quantum/iqsharp-base:0.10.1912.0501`, and that `mcr.microsoft.com/quantum/iqsharp-base:0.10.1911.1607` works well on mybinder.org. Both images seem to work well when running the images locally.

**Comment by rmshaffer** [comment]
Two fixes have been made here:
- in the base IQ# image: https://github.com/microsoft/iqsharp/commit/84bfc6b1da501e31fff93b6a544256eb4c573ab3
- in the Katas image, by @vxfield: https://github.com/microsoft/QuantumKatas/commit/6ddf60485ed3ad5bffe463cc85548ed1915e8c94

Performance on MyBinder is much improved with these two fixes. First cell execution times are typically only a couple of seconds or less.
