### ISSUE TITLE
Swagger / Swashbuckle for HTTP API

### ISSUE THREAD

**Issue by codingupastorm** [microsoft/iqsharp#87]
The HTTP API could have a pretty UI. Developers would be able to manually test the different available methods quite easily through a single interface rather than reading controller code. Could foster more interoperability projects and generally make the server easier to use.

We could use swagger / swashbuckle to automatically generate this interface. It might look something like this in case you are not familiar with swagger: https://petstore.swagger.io/

I wouldn't want to pollute your solution but this is probably something I'll add for myself anyway - let me know if you think it would be useful.

**Comment by rmshaffer** [comment]
Thanks @codingupastorm for the suggestion and enthusiasm! This doesn't quite fit with the goals of IQ#, as we don't plan to support the underlying HTTP calls as a way to interface with the IQ# kernel directly, outside the context of Jupyter. Of course, you're more than welcome to continue work on your own and share with us anything you've built!
